// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using PayrollAPI.Data;

#nullable disable

namespace PayrollAPI.Migrations.HRMDBConnectMigrations
{
    [DbContext(typeof(HRMDBConnect))]
    [Migration("20241101101239_hrmtable_init")]
    partial class hrmtable_init
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.14")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("PayrollAPI.Models.HRM.EmployeeLeave", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<int>("companyCode")
                        .HasColumnType("int");

                    b.HasKey("id");

                    b.ToTable("EmployeeLeave");
                });
#pragma warning restore 612, 618
        }
    }
}
