// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using PayrollAPI.Data;

#nullable disable

namespace PayrollAPI.Migrations.HRMDBConnectMigrations
{
    [DbContext(typeof(HRMDBConnect))]
    [Migration("20241104104055_allow_null_values_to_Lastupdate")]
    partial class allow_null_values_to_Lastupdate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.14")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("PayrollAPI.Models.HRM.EmployeeLeave", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<int>("companyCode")
                        .HasColumnType("int");

                    b.HasKey("id");

                    b.ToTable("EmployeeLeave");
                });

            modelBuilder.Entity("PayrollAPI.Models.HRM.LeaveBalance", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<decimal>("allocatedLeaves")
                        .HasColumnType("decimal(4, 1)");

                    b.Property<decimal>("carryForwardLeaves")
                        .HasColumnType("decimal(4, 1)");

                    b.Property<string>("createdBy")
                        .HasColumnType("varchar(10)");

                    b.Property<DateTime>("createdDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime(6)")
                        .HasDefaultValueSql("(CURDATE())");

                    b.Property<DateTime>("createdTime")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime(6)")
                        .HasDefaultValueSql("(CURTIME())");

                    b.Property<int>("epf")
                        .HasColumnType("int");

                    b.Property<string>("lastUpdateBy")
                        .HasColumnType("varchar(10)");

                    b.Property<DateTime?>("lastUpdateDate")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime?>("lastUpdateTime")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("leaveTypeId")
                        .HasColumnType("int");

                    b.Property<decimal>("remainingLeaves")
                        .HasColumnType("decimal(4, 1)");

                    b.Property<decimal>("usedLeaves")
                        .HasColumnType("decimal(4, 1)");

                    b.Property<int>("year")
                        .HasColumnType("int");

                    b.HasKey("id");

                    b.HasIndex("leaveTypeId");

                    b.ToTable("LeaveBalance");
                });

            modelBuilder.Entity("PayrollAPI.Models.HRM.LeaveRequest", b =>
                {
                    b.Property<int>("leaveRequestId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("actionedBy")
                        .HasColumnType("varchar(10)");

                    b.Property<DateTime>("actionedDate")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime>("actionedTime")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime>("createdDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime(6)")
                        .HasDefaultValueSql("(CURDATE())");

                    b.Property<DateTime>("createdTime")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime(6)")
                        .HasDefaultValueSql("(CURTIME())");

                    b.Property<DateTime>("endDate")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("epf")
                        .HasColumnType("int");

                    b.Property<bool>("isHalfDay")
                        .HasColumnType("boolean");

                    b.Property<string>("lastUpdateBy")
                        .HasColumnType("varchar(10)");

                    b.Property<DateTime?>("lastUpdateDate")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime?>("lastUpdateTime")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("leaveTypeId")
                        .HasColumnType("int");

                    b.Property<DateTime>("lieuLeaveDate")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("reason")
                        .HasColumnType("varchar(250)");

                    b.Property<DateTime>("startDate")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("status")
                        .IsRequired()
                        .HasColumnType("varchar(10)");

                    b.HasKey("leaveRequestId");

                    b.HasIndex("leaveTypeId");

                    b.ToTable("LeaveRequest");
                });

            modelBuilder.Entity("PayrollAPI.Models.HRM.LeaveType", b =>
                {
                    b.Property<int>("leaveTypeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<bool>("carryForwardAllowed")
                        .HasColumnType("boolean");

                    b.Property<string>("createdBy")
                        .HasColumnType("varchar(10)");

                    b.Property<DateTime>("createdDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime(6)")
                        .HasDefaultValueSql("(CURDATE())");

                    b.Property<DateTime>("createdTime")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime(6)")
                        .HasDefaultValueSql("(CURTIME())");

                    b.Property<string>("description")
                        .IsRequired()
                        .HasColumnType("varchar(250)");

                    b.Property<string>("lastUpdateBy")
                        .HasColumnType("varchar(10)");

                    b.Property<DateTime?>("lastUpdateDate")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime?>("lastUpdateTime")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("leaveTypeName")
                        .IsRequired()
                        .HasColumnType("varchar(50)");

                    b.Property<decimal>("maxDays")
                        .HasColumnType("decimal(4, 1)");

                    b.HasKey("leaveTypeId");

                    b.ToTable("LeaveType");
                });

            modelBuilder.Entity("PayrollAPI.Models.HRM.LeaveBalance", b =>
                {
                    b.HasOne("PayrollAPI.Models.HRM.LeaveType", "leaveType")
                        .WithMany()
                        .HasForeignKey("leaveTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("leaveType");
                });

            modelBuilder.Entity("PayrollAPI.Models.HRM.LeaveRequest", b =>
                {
                    b.HasOne("PayrollAPI.Models.HRM.LeaveType", "leaveType")
                        .WithMany("leaveRequests")
                        .HasForeignKey("leaveTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("leaveType");
                });

            modelBuilder.Entity("PayrollAPI.Models.HRM.LeaveType", b =>
                {
                    b.Navigation("leaveRequests");
                });
#pragma warning restore 612, 618
        }
    }
}
