// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using PayrollAPI.Data;

#nullable disable

namespace PayrollAPI.Migrations.HRMDBConnectMigrations
{
    [DbContext(typeof(HRMDBConnect))]
    [Migration("20241120093709_addReftoNotification")]
    partial class addReftoNotification
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.14")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("PayrollAPI.Models.HRM.AdvancePayment", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<decimal>("amount")
                        .HasColumnType("decimal(10, 2)");

                    b.Property<string>("createdBy")
                        .HasColumnType("varchar(10)");

                    b.Property<DateTime>("createdDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime(6)")
                        .HasDefaultValueSql("(CURDATE())");

                    b.Property<DateTime>("createdTime")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime(6)")
                        .HasDefaultValueSql("(CURTIME())");

                    b.Property<string>("epf")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<bool>("isFullAmount")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("lastUpdateBy")
                        .HasColumnType("varchar(10)");

                    b.Property<DateTime?>("lastUpdateDate")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime?>("lastUpdateTime")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("period")
                        .HasColumnType("int");

                    b.Property<int>("status")
                        .HasColumnType("int");

                    b.HasKey("id");

                    b.ToTable("AdvancePayment");
                });

            modelBuilder.Entity("PayrollAPI.Models.HRM.EmpApprovalWorkflow", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<int?>("approvalLevelsid")
                        .HasColumnType("int");

                    b.Property<int?>("approverIdid")
                        .HasColumnType("int");

                    b.Property<int>("empApprovalIdid")
                        .HasColumnType("int");

                    b.HasKey("id");

                    b.HasIndex("approvalLevelsid");

                    b.HasIndex("approverIdid");

                    b.HasIndex("empApprovalIdid");

                    b.ToTable("EmpApprovalWorkflow");
                });

            modelBuilder.Entity("PayrollAPI.Models.HRM.EmpApprovals", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("createdBy")
                        .HasColumnType("varchar(10)");

                    b.Property<DateTime>("createdDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime(6)")
                        .HasDefaultValueSql("(CURDATE())");

                    b.Property<DateTime>("createdTime")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime(6)")
                        .HasDefaultValueSql("(CURTIME())");

                    b.Property<int>("epf")
                        .HasColumnType("int");

                    b.Property<string>("lastUpdateBy")
                        .HasColumnType("varchar(10)");

                    b.Property<DateTime?>("lastUpdateDate")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime?>("lastUpdateTime")
                        .HasColumnType("datetime(6)");

                    b.Property<int?>("level")
                        .HasColumnType("int");

                    b.HasKey("id");

                    b.ToTable("EmpApprovals");
                });

            modelBuilder.Entity("PayrollAPI.Models.HRM.LeaveApproval", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<int>("approver_idid")
                        .HasColumnType("int");

                    b.Property<string>("comments")
                        .HasColumnType("varchar(100)");

                    b.Property<DateTime>("createdDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime(6)")
                        .HasDefaultValueSql("(CURDATE())");

                    b.Property<DateTime>("createdTime")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime(6)")
                        .HasDefaultValueSql("(CURTIME())");

                    b.Property<string>("epf")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("levelid")
                        .HasColumnType("int");

                    b.Property<int>("requestIdleaveRequestId")
                        .HasColumnType("int");

                    b.Property<string>("status")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("id");

                    b.HasIndex("approver_idid");

                    b.HasIndex("levelid");

                    b.HasIndex("requestIdleaveRequestId");

                    b.ToTable("LeaveApproval");
                });

            modelBuilder.Entity("PayrollAPI.Models.HRM.LeaveBalance", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<decimal>("allocatedLeaves")
                        .HasColumnType("decimal(4, 1)");

                    b.Property<decimal>("carryForwardLeaves")
                        .HasColumnType("decimal(4, 1)");

                    b.Property<string>("createdBy")
                        .HasColumnType("varchar(10)");

                    b.Property<DateTime>("createdDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime(6)")
                        .HasDefaultValueSql("(CURDATE())");

                    b.Property<DateTime>("createdTime")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime(6)")
                        .HasDefaultValueSql("(CURTIME())");

                    b.Property<int>("epf")
                        .HasColumnType("int");

                    b.Property<string>("lastUpdateBy")
                        .HasColumnType("varchar(10)");

                    b.Property<DateTime?>("lastUpdateDate")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime?>("lastUpdateTime")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("leaveTypeId")
                        .HasColumnType("int");

                    b.Property<decimal>("remainingLeaves")
                        .HasColumnType("decimal(4, 1)");

                    b.Property<decimal>("usedLeaves")
                        .HasColumnType("decimal(4, 1)");

                    b.Property<int>("year")
                        .HasColumnType("int");

                    b.HasKey("id");

                    b.HasIndex("leaveTypeId");

                    b.ToTable("LeaveBalance");
                });

            modelBuilder.Entity("PayrollAPI.Models.HRM.LeaveRequest", b =>
                {
                    b.Property<int>("leaveRequestId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("actingDelegate")
                        .HasColumnType("longtext");

                    b.Property<string>("actingDelegateApprovalStatus")
                        .HasColumnType("longtext");

                    b.Property<DateTime?>("actingDelegateApprovedDate")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime?>("actingDelegateApprovedTime")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("actionedBy")
                        .HasColumnType("varchar(10)");

                    b.Property<DateTime>("createdDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime(6)")
                        .HasDefaultValueSql("(CURDATE())");

                    b.Property<DateTime>("createdTime")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime(6)")
                        .HasDefaultValueSql("(CURTIME())");

                    b.Property<int>("currentLevel")
                        .HasColumnType("int");

                    b.Property<DateTime>("endDate")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("epf")
                        .HasColumnType("int");

                    b.Property<string>("finalStatus")
                        .HasColumnType("longtext");

                    b.Property<int?>("halfDayType")
                        .HasColumnType("int");

                    b.Property<bool>("isHalfDay")
                        .HasColumnType("boolean");

                    b.Property<string>("lastUpdateBy")
                        .HasColumnType("varchar(10)");

                    b.Property<DateTime?>("lastUpdateDate")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime?>("lastUpdateTime")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("leaveTypeId")
                        .HasColumnType("int");

                    b.Property<DateTime>("lieuLeaveDate")
                        .HasColumnType("datetime(6)");

                    b.Property<decimal?>("noOfDays")
                        .HasColumnType("decimal(4, 1)");

                    b.Property<string>("reason")
                        .HasColumnType("varchar(250)");

                    b.Property<string>("requestStatus")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<DateTime>("startDate")
                        .HasColumnType("datetime(6)");

                    b.HasKey("leaveRequestId");

                    b.HasIndex("leaveTypeId");

                    b.ToTable("LeaveRequest");
                });

            modelBuilder.Entity("PayrollAPI.Models.HRM.LeaveType", b =>
                {
                    b.Property<int>("leaveTypeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<bool>("carryForwardAllowed")
                        .HasColumnType("boolean");

                    b.Property<string>("createdBy")
                        .HasColumnType("varchar(10)");

                    b.Property<DateTime>("createdDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime(6)")
                        .HasDefaultValueSql("(CURDATE())");

                    b.Property<DateTime>("createdTime")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime(6)")
                        .HasDefaultValueSql("(CURTIME())");

                    b.Property<string>("description")
                        .IsRequired()
                        .HasColumnType("varchar(250)");

                    b.Property<string>("lastUpdateBy")
                        .HasColumnType("varchar(10)");

                    b.Property<DateTime?>("lastUpdateDate")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime?>("lastUpdateTime")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("leaveTypeName")
                        .IsRequired()
                        .HasColumnType("varchar(50)");

                    b.Property<decimal>("maxDays")
                        .HasColumnType("decimal(4, 1)");

                    b.HasKey("leaveTypeId");

                    b.ToTable("LeaveType");
                });

            modelBuilder.Entity("PayrollAPI.Models.HRM.Notification", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<DateTime>("createdDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime(6)")
                        .HasDefaultValueSql("(CURDATE())");

                    b.Property<string>("description")
                        .HasColumnType("longtext");

                    b.Property<int>("epf")
                        .HasColumnType("int");

                    b.Property<bool>("markAsRead")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("reference")
                        .HasColumnType("varchar(6)");

                    b.Property<string>("status")
                        .HasColumnType("varchar(10)");

                    b.Property<string>("target")
                        .HasColumnType("varchar(10)");

                    b.Property<int>("type")
                        .HasColumnType("int");

                    b.HasKey("id");

                    b.ToTable("Notification");
                });

            modelBuilder.Entity("PayrollAPI.Models.HRM.Supervisor", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("createdBy")
                        .HasColumnType("varchar(10)");

                    b.Property<DateTime>("createdDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime(6)")
                        .HasDefaultValueSql("(CURDATE())");

                    b.Property<DateTime>("createdTime")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime(6)")
                        .HasDefaultValueSql("(CURTIME())");

                    b.Property<string>("epf")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<bool>("isActive")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("lastUpdateBy")
                        .HasColumnType("varchar(10)");

                    b.Property<DateTime?>("lastUpdateDate")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime?>("lastUpdateTime")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("userId")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("id");

                    b.ToTable("Supervisor");
                });

            modelBuilder.Entity("PayrollAPI.Models.HRM.WorkflowTypes", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("createdBy")
                        .HasColumnType("varchar(10)");

                    b.Property<DateTime>("createdDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime(6)")
                        .HasDefaultValueSql("(CURDATE())");

                    b.Property<DateTime>("createdTime")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime(6)")
                        .HasDefaultValueSql("(CURTIME())");

                    b.Property<string>("lastUpdateBy")
                        .HasColumnType("varchar(10)");

                    b.Property<DateTime?>("lastUpdateDate")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime?>("lastUpdateTime")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("levelName")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("id");

                    b.ToTable("WorkflowTypes");
                });

            modelBuilder.Entity("PayrollAPI.Models.HRM.EmpApprovalWorkflow", b =>
                {
                    b.HasOne("PayrollAPI.Models.HRM.WorkflowTypes", "approvalLevels")
                        .WithMany()
                        .HasForeignKey("approvalLevelsid");

                    b.HasOne("PayrollAPI.Models.HRM.Supervisor", "approverId")
                        .WithMany()
                        .HasForeignKey("approverIdid");

                    b.HasOne("PayrollAPI.Models.HRM.EmpApprovals", "empApprovalId")
                        .WithMany("approvalWorkflowsId")
                        .HasForeignKey("empApprovalIdid")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("approvalLevels");

                    b.Navigation("approverId");

                    b.Navigation("empApprovalId");
                });

            modelBuilder.Entity("PayrollAPI.Models.HRM.LeaveApproval", b =>
                {
                    b.HasOne("PayrollAPI.Models.HRM.Supervisor", "approver_id")
                        .WithMany()
                        .HasForeignKey("approver_idid")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PayrollAPI.Models.HRM.WorkflowTypes", "level")
                        .WithMany()
                        .HasForeignKey("levelid")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PayrollAPI.Models.HRM.LeaveRequest", "requestId")
                        .WithMany()
                        .HasForeignKey("requestIdleaveRequestId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("approver_id");

                    b.Navigation("level");

                    b.Navigation("requestId");
                });

            modelBuilder.Entity("PayrollAPI.Models.HRM.LeaveBalance", b =>
                {
                    b.HasOne("PayrollAPI.Models.HRM.LeaveType", "leaveType")
                        .WithMany()
                        .HasForeignKey("leaveTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("leaveType");
                });

            modelBuilder.Entity("PayrollAPI.Models.HRM.LeaveRequest", b =>
                {
                    b.HasOne("PayrollAPI.Models.HRM.LeaveType", "leaveType")
                        .WithMany("leaveRequests")
                        .HasForeignKey("leaveTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("leaveType");
                });

            modelBuilder.Entity("PayrollAPI.Models.HRM.EmpApprovals", b =>
                {
                    b.Navigation("approvalWorkflowsId");
                });

            modelBuilder.Entity("PayrollAPI.Models.HRM.LeaveType", b =>
                {
                    b.Navigation("leaveRequests");
                });
#pragma warning restore 612, 618
        }
    }
}
