// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using PayrollAPI.Data;

#nullable disable

namespace PayrollAPI.Migrations
{
    [DbContext(typeof(DBConnect))]
    [Migration("20240102023219_02.01.2023-1")]
    partial class _020120231
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("PayrollAPI.Models.Calculation", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("calCode")
                        .HasColumnType("varchar(5)");

                    b.Property<string>("calDescription")
                        .HasColumnType("varchar(500)");

                    b.Property<string>("calFormula")
                        .HasColumnType("varchar(500)");

                    b.Property<int>("companyCode")
                        .HasColumnType("int");

                    b.Property<string>("createdBy")
                        .HasColumnType("varchar(10)");

                    b.Property<DateTime>("createdDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime(6)")
                        .HasDefaultValueSql("(CURDATE())");

                    b.Property<DateTime>("createdTime")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime(6)")
                        .HasDefaultValueSql("(CURTIME())");

                    b.Property<string>("lastUpdateBy")
                        .HasColumnType("varchar(10)");

                    b.Property<DateTime?>("lastUpdateDate")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime?>("lastUpdateTime")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("payCategory")
                        .HasColumnType("varchar(2)");

                    b.Property<int>("payCode")
                        .HasColumnType("int");

                    b.Property<int>("sequence")
                        .HasColumnType("int");

                    b.Property<bool>("status")
                        .HasColumnType("boolean");

                    b.HasKey("id");

                    b.ToTable("Calculation");
                });

            modelBuilder.Entity("PayrollAPI.Models.EPF_ETF", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<decimal>("comp_contribution")
                        .HasColumnType("decimal(10, 2)");

                    b.Property<int>("companyCode")
                        .HasColumnType("int");

                    b.Property<string>("createdBy")
                        .HasColumnType("varchar(10)");

                    b.Property<DateTime>("createdDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime(6)")
                        .HasDefaultValueSql("(CURDATE())");

                    b.Property<DateTime>("createdTime")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime(6)")
                        .HasDefaultValueSql("(CURTIME())");

                    b.Property<string>("empName")
                        .HasColumnType("varchar(200)");

                    b.Property<decimal>("emp_contribution")
                        .HasColumnType("decimal(10, 2)");

                    b.Property<string>("epf")
                        .IsRequired()
                        .HasColumnType("varchar(6)");

                    b.Property<decimal>("epfGross")
                        .HasColumnType("decimal(10, 2)");

                    b.Property<decimal>("etf")
                        .HasColumnType("decimal(10, 2)");

                    b.Property<string>("grade")
                        .HasColumnType("varchar(5)");

                    b.Property<int>("location")
                        .HasColumnType("int");

                    b.Property<decimal?>("lumpsumTax")
                        .HasColumnType("decimal(10, 2)");

                    b.Property<int>("period")
                        .HasColumnType("int");

                    b.Property<decimal>("tax")
                        .HasColumnType("decimal(10, 2)");

                    b.Property<decimal>("taxableGross")
                        .HasColumnType("decimal(10, 2)");

                    b.HasKey("id");

                    b.ToTable("EPF_ETF");
                });

            modelBuilder.Entity("PayrollAPI.Models.EmpSpecialRate", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("calCode")
                        .HasColumnType("varchar(5)");

                    b.Property<int>("companyCode")
                        .HasColumnType("int");

                    b.Property<string>("costCenter")
                        .HasColumnType("varchar(50)");

                    b.Property<string>("createdBy")
                        .HasColumnType("varchar(10)");

                    b.Property<DateTime>("createdDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime(6)")
                        .HasDefaultValueSql("(CURDATE())");

                    b.Property<DateTime>("createdTime")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime(6)")
                        .HasDefaultValueSql("(CURTIME())");

                    b.Property<string>("epf")
                        .IsRequired()
                        .HasColumnType("varchar(6)");

                    b.Property<string>("lastUpdateBy")
                        .HasColumnType("varchar(10)");

                    b.Property<DateTime>("lastUpdateDate")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime>("lastUpdateTime")
                        .HasColumnType("datetime(6)");

                    b.Property<int?>("location")
                        .HasColumnType("int");

                    b.Property<int>("payCode")
                        .HasColumnType("int");

                    b.Property<decimal>("rate")
                        .HasColumnType("decimal(3, 2)");

                    b.Property<bool>("status")
                        .HasColumnType("boolean");

                    b.HasKey("id");

                    b.ToTable("EmpSpecialRate");
                });

            modelBuilder.Entity("PayrollAPI.Models.Employee_Data", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("accountNo")
                        .HasColumnType("varchar(15)");

                    b.Property<int>("bankCode")
                        .HasColumnType("int");

                    b.Property<int>("branchCode")
                        .HasColumnType("int");

                    b.Property<string>("changeBy")
                        .HasColumnType("varchar(10)");

                    b.Property<DateTime?>("changeDate")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("companyCode")
                        .HasColumnType("int");

                    b.Property<string>("costCenter")
                        .HasColumnType("varchar(6)");

                    b.Property<string>("empGrade")
                        .HasColumnType("varchar(5)");

                    b.Property<string>("empName")
                        .HasColumnType("varchar(500)");

                    b.Property<string>("epf")
                        .IsRequired()
                        .HasColumnType("varchar(6)");

                    b.Property<int>("gradeCode")
                        .HasColumnType("int");

                    b.Property<bool?>("isPaysheetGenerated")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValueSql("1");

                    b.Property<int>("location")
                        .HasColumnType("int");

                    b.Property<int>("paymentType")
                        .HasColumnType("int");

                    b.Property<int>("period")
                        .HasColumnType("int");

                    b.Property<bool?>("status")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValueSql("1");

                    b.HasKey("id");

                    b.ToTable("Employee_Data");
                });

            modelBuilder.Entity("PayrollAPI.Models.LoginInfo", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<int>("companyCode")
                        .HasColumnType("int");

                    b.Property<int>("costCenter")
                        .HasColumnType("int");

                    b.Property<bool>("isActive")
                        .HasColumnType("boolean");

                    b.Property<DateTime>("loginDateTime")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime>("loginTime")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("refreshToken")
                        .HasColumnType("varchar(300)");

                    b.Property<string>("tokenID")
                        .HasColumnType("varchar(300)");

                    b.Property<string>("userID")
                        .HasColumnType("varchar(10)");

                    b.HasKey("id");

                    b.ToTable("LoginInfo");
                });

            modelBuilder.Entity("PayrollAPI.Models.PayCode", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("calCode")
                        .HasColumnType("varchar(5)");

                    b.Property<int>("companyCode")
                        .HasColumnType("int");

                    b.Property<string>("createdBy")
                        .HasColumnType("varchar(10)");

                    b.Property<DateTime>("createdDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime(6)")
                        .HasDefaultValueSql("(CURDATE())");

                    b.Property<DateTime>("createdTime")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime(6)")
                        .HasDefaultValueSql("(CURTIME())");

                    b.Property<string>("description")
                        .HasColumnType("varchar(100)");

                    b.Property<bool>("isTaxableGross")
                        .HasColumnType("boolean");

                    b.Property<string>("lastUpdateBy")
                        .HasColumnType("varchar(10)");

                    b.Property<DateTime?>("lastUpdateDate")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime?>("lastUpdateTime")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("payCategory")
                        .HasColumnType("varchar(2)");

                    b.Property<int>("payCode")
                        .HasColumnType("int");

                    b.Property<decimal>("rate")
                        .HasColumnType("decimal(3, 2)");

                    b.HasKey("id");

                    b.ToTable("PayCode");
                });

            modelBuilder.Entity("PayrollAPI.Models.Payroll_Data", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<decimal>("amount")
                        .HasColumnType("decimal(10, 2)");

                    b.Property<decimal>("balanceAmount")
                        .HasColumnType("decimal(10, 2)");

                    b.Property<string>("calCode")
                        .HasColumnType("varchar(5)");

                    b.Property<int>("companyCode")
                        .HasColumnType("int");

                    b.Property<string>("costCenter")
                        .HasColumnType("varchar(6)");

                    b.Property<bool?>("displayOnPaySheet")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValueSql("1");

                    b.Property<string>("epf")
                        .IsRequired()
                        .HasColumnType("varchar(6)");

                    b.Property<float>("epfConRate")
                        .HasColumnType("float");

                    b.Property<decimal>("epfContribution")
                        .HasColumnType("decimal(10, 2)");

                    b.Property<int>("location")
                        .HasColumnType("int");

                    b.Property<float>("othours")
                        .HasColumnType("float");

                    b.Property<string>("payCategory")
                        .HasColumnType("varchar(2)");

                    b.Property<int>("payCode")
                        .HasColumnType("int");

                    b.Property<string>("payCodeType")
                        .HasColumnType("varchar(2)");

                    b.Property<string>("paytype")
                        .HasColumnType("varchar(1)");

                    b.Property<int>("period")
                        .HasColumnType("int");

                    b.Property<float>("taxConRate")
                        .HasColumnType("float");

                    b.Property<decimal>("taxContribution")
                        .HasColumnType("decimal(10, 2)");

                    b.HasKey("id");

                    b.ToTable("Payroll_Data");
                });

            modelBuilder.Entity("PayrollAPI.Models.Payrun", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("approvedBy")
                        .HasColumnType("varchar(10)");

                    b.Property<DateTime>("approvedDate")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime>("approvedTime")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("companyCode")
                        .HasColumnType("int");

                    b.Property<int>("noOfEmployees")
                        .HasColumnType("int");

                    b.Property<int>("noOfRecords")
                        .HasColumnType("int");

                    b.Property<string>("payrunBy")
                        .HasColumnType("varchar(10)");

                    b.Property<DateTime>("payrunDate")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("payrunStatus")
                        .HasColumnType("varchar(10)");

                    b.Property<DateTime>("payrunTime")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("period")
                        .HasColumnType("int");

                    b.HasKey("id");

                    b.ToTable("Payrun");
                });

            modelBuilder.Entity("PayrollAPI.Models.SAPTotPayCode", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("calCode")
                        .HasColumnType("varchar(5)");

                    b.Property<int>("companyCode")
                        .HasColumnType("int");

                    b.Property<string>("createdBy")
                        .HasColumnType("varchar(10)");

                    b.Property<DateTime>("createdDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime(6)")
                        .HasDefaultValueSql("(CURDATE())");

                    b.Property<DateTime>("createdTime")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime(6)")
                        .HasDefaultValueSql("(CURTIME())");

                    b.Property<int>("payCode")
                        .HasColumnType("int");

                    b.Property<string>("payType")
                        .HasColumnType("varchar(1)");

                    b.Property<int>("period")
                        .HasColumnType("int");

                    b.Property<int>("totCount")
                        .HasColumnType("int");

                    b.Property<decimal>("totalAmount")
                        .HasColumnType("decimal(10, 2)");

                    b.HasKey("id");

                    b.ToTable("SAPTotPayCode");
                });

            modelBuilder.Entity("PayrollAPI.Models.Special_Tax_Emp", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("calFormula")
                        .HasColumnType("varchar(500)");

                    b.Property<int>("companyCode")
                        .HasColumnType("int");

                    b.Property<string>("costCenter")
                        .HasColumnType("varchar(50)");

                    b.Property<string>("createdBy")
                        .HasColumnType("varchar(10)");

                    b.Property<DateTime>("createdDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime(6)")
                        .HasDefaultValueSql("(CURDATE())");

                    b.Property<DateTime>("createdTime")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime(6)")
                        .HasDefaultValueSql("(CURTIME())");

                    b.Property<string>("epf")
                        .IsRequired()
                        .HasColumnType("varchar(6)");

                    b.Property<string>("lastUpdateBy")
                        .HasColumnType("varchar(10)");

                    b.Property<DateTime>("lastUpdateDate")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime>("lastUpdateTime")
                        .HasColumnType("datetime(6)");

                    b.Property<int?>("location")
                        .HasColumnType("int");

                    b.Property<bool>("status")
                        .HasColumnType("boolean");

                    b.HasKey("id");

                    b.ToTable("Special_Tax_Emp");
                });

            modelBuilder.Entity("PayrollAPI.Models.Tax_Calculation", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("calFormula")
                        .HasColumnType("varchar(500)");

                    b.Property<int>("companyCode")
                        .HasColumnType("int");

                    b.Property<string>("createdBy")
                        .HasColumnType("varchar(10)");

                    b.Property<DateTime>("createdDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime(6)")
                        .HasDefaultValueSql("(CURDATE())");

                    b.Property<DateTime>("createdTime")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime(6)")
                        .HasDefaultValueSql("(CURTIME())");

                    b.Property<string>("description")
                        .HasColumnType("varchar(500)");

                    b.Property<string>("lastUpdateBy")
                        .HasColumnType("varchar(10)");

                    b.Property<DateTime?>("lastUpdateDate")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime?>("lastUpdateTime")
                        .HasColumnType("datetime(6)");

                    b.Property<decimal>("range")
                        .HasColumnType("decimal(10, 2)");

                    b.Property<bool>("status")
                        .HasColumnType("boolean");

                    b.HasKey("id");

                    b.ToTable("Tax_Calculation");
                });

            modelBuilder.Entity("PayrollAPI.Models.Temp_Employee", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("accountNo")
                        .HasColumnType("varchar(15)");

                    b.Property<int>("bankCode")
                        .HasColumnType("int");

                    b.Property<int>("branchCode")
                        .HasColumnType("int");

                    b.Property<int>("companyCode")
                        .HasColumnType("int");

                    b.Property<string>("costCenter")
                        .HasColumnType("varchar(6)");

                    b.Property<string>("createdBy")
                        .HasColumnType("varchar(10)");

                    b.Property<DateTime>("createdDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime(6)")
                        .HasDefaultValueSql("(CURDATE())");

                    b.Property<DateTime>("createdTime")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime(6)")
                        .HasDefaultValueSql("(CURTIME())");

                    b.Property<string>("empGrade")
                        .HasColumnType("varchar(5)");

                    b.Property<string>("empName")
                        .HasColumnType("varchar(100)");

                    b.Property<string>("epf")
                        .IsRequired()
                        .HasColumnType("varchar(6)");

                    b.Property<int>("gradeCode")
                        .HasColumnType("int");

                    b.Property<int>("location")
                        .HasColumnType("int");

                    b.Property<int>("paymentType")
                        .HasColumnType("int");

                    b.Property<int>("period")
                        .HasColumnType("int");

                    b.HasKey("id");

                    b.ToTable("Temp_Employee");
                });

            modelBuilder.Entity("PayrollAPI.Models.Temp_Payroll", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<decimal>("amount")
                        .HasColumnType("decimal(10, 2)");

                    b.Property<decimal>("balanceamount")
                        .HasColumnType("decimal(10, 2)");

                    b.Property<string>("calCode")
                        .HasColumnType("varchar(5)");

                    b.Property<int>("companyCode")
                        .HasColumnType("int");

                    b.Property<string>("costCenter")
                        .HasColumnType("varchar(6)");

                    b.Property<DateTime>("createdDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime(6)")
                        .HasDefaultValueSql("(CURDATE())");

                    b.Property<DateTime>("createdTime")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime(6)")
                        .HasDefaultValueSql("(CURTIME())");

                    b.Property<string>("epf")
                        .IsRequired()
                        .HasColumnType("varchar(6)");

                    b.Property<float>("epfConRate")
                        .HasColumnType("float");

                    b.Property<int>("location")
                        .HasColumnType("int");

                    b.Property<float>("othours")
                        .HasColumnType("float");

                    b.Property<string>("payCategory")
                        .HasColumnType("varchar(2)");

                    b.Property<int>("payCode")
                        .HasColumnType("int");

                    b.Property<string>("payCodeType")
                        .HasColumnType("varchar(2)");

                    b.Property<string>("paytype")
                        .HasColumnType("varchar(1)");

                    b.Property<int>("period")
                        .HasColumnType("int");

                    b.Property<float>("taxConRate")
                        .HasColumnType("float");

                    b.HasKey("id");

                    b.ToTable("Temp_Payroll");
                });

            modelBuilder.Entity("PayrollAPI.Models.TotPayCode", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("calCode")
                        .HasColumnType("varchar(5)");

                    b.Property<int>("companyCode")
                        .HasColumnType("int");

                    b.Property<string>("createdBy")
                        .HasColumnType("varchar(10)");

                    b.Property<DateTime>("createdDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime(6)")
                        .HasDefaultValueSql("(CURDATE())");

                    b.Property<DateTime>("createdTime")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime(6)")
                        .HasDefaultValueSql("(CURTIME())");

                    b.Property<int>("payCode")
                        .HasColumnType("int");

                    b.Property<int>("period")
                        .HasColumnType("int");

                    b.Property<decimal>("total")
                        .HasColumnType("decimal(10, 2)");

                    b.HasKey("id");

                    b.ToTable("TotPayCode");
                });

            modelBuilder.Entity("PayrollAPI.Models.Unrecovered", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<decimal>("amount")
                        .HasColumnType("decimal(10, 2)");

                    b.Property<string>("calCode")
                        .HasColumnType("varchar(5)");

                    b.Property<int>("companyCode")
                        .HasColumnType("int");

                    b.Property<string>("costCenter")
                        .HasColumnType("varchar(6)");

                    b.Property<DateTime>("createdDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime(6)")
                        .HasDefaultValueSql("(CURDATE())");

                    b.Property<DateTime>("createdTime")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime(6)")
                        .HasDefaultValueSql("(CURTIME())");

                    b.Property<string>("epf")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("location")
                        .HasColumnType("int");

                    b.Property<string>("payCategory")
                        .HasColumnType("varchar(2)");

                    b.Property<int>("payCode")
                        .HasColumnType("int");

                    b.Property<int>("period")
                        .HasColumnType("int");

                    b.HasKey("id");

                    b.ToTable("Unrecovered");
                });

            modelBuilder.Entity("PayrollAPI.Models.User", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<int>("companyCode")
                        .HasColumnType("int");

                    b.Property<string>("costCenter")
                        .HasColumnType("varchar(6)");

                    b.Property<string>("createdBy")
                        .HasColumnType("varchar(10)");

                    b.Property<DateTime>("createdDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime(6)")
                        .HasDefaultValueSql("(CURDATE())");

                    b.Property<DateTime>("createdTime")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime(6)")
                        .HasDefaultValueSql("(CURTIME())");

                    b.Property<string>("empName")
                        .HasColumnType("varchar(60)");

                    b.Property<string>("epf")
                        .IsRequired()
                        .HasColumnType("varchar(6)");

                    b.Property<string>("lastUpdateBy")
                        .HasColumnType("varchar(10)");

                    b.Property<DateTime>("lastUpdateDate")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime>("lastUpdateTime")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("pwdHash")
                        .HasColumnType("varchar(200)");

                    b.Property<string>("pwdSalt")
                        .HasColumnType("varchar(50)");

                    b.Property<string>("role")
                        .HasColumnType("varchar(6)");

                    b.Property<bool>("status")
                        .HasColumnType("boolean");

                    b.Property<string>("userID")
                        .HasColumnType("varchar(10)");

                    b.HasKey("id");

                    b.ToTable("User");
                });
#pragma warning restore 612, 618
        }
    }
}
